/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.patrickayoup.googletasksdownloader.view;

import javax.swing.*;

/**
 *
 * @author patrickayoup
 */
public class AuthView extends javax.swing.JFrame {

    /**
     * Creates new form AuthView
     */
    public AuthView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        titleSeparator = new javax.swing.JSeparator();
        instructionTextPane = new javax.swing.JTextPane();
        launchSiteButton = new javax.swing.JButton();
        authorizationCodeLabel = new javax.swing.JLabel();
        authorizationCodeTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Welcome to Google Tasks Downloader");

        instructionTextPane.setText("To give Google Tasks Downloader permission to access your tasks and task lists, click the \"Launch Authentication Site\" button below. This will launch an authorization page from Google where you must provide Google with permission to allow Google Tasks Downloader to access your tasks. This authentication process uses OAuth2. This means that Google Tasks Downloader will never see your login credentials.\n\nOnce Google has validated your credentials, they will display an authorization code which you must copy and paste into the text box below and click \"Submit\".");
        instructionTextPane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        instructionTextPane.setFocusable(false);
        instructionTextPane.setHighlighter(null);

        launchSiteButton.setText("Launch Authentication Site");

        authorizationCodeLabel.setText("Authorization Code:");

        submitButton.setText("Submit");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(launchSiteButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(titleLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                        .add(9, 9, 9))
                    .add(instructionTextPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, titleSeparator)
                    .add(layout.createSequentialGroup()
                        .add(authorizationCodeLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(authorizationCodeTextField))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(submitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(titleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(titleSeparator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(instructionTextPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(launchSiteButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(authorizationCodeLabel)
                    .add(authorizationCodeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(submitButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorizationCodeLabel;
    private javax.swing.JTextField authorizationCodeTextField;
    private javax.swing.JTextPane instructionTextPane;
    private javax.swing.JButton launchSiteButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JSeparator titleSeparator;
    // End of variables declaration//GEN-END:variables

    public JLabel getAuthorizationCodeLabel() {
        return authorizationCodeLabel;
    }

    public JTextField getAuthorizationCodeTextField() {
        return authorizationCodeTextField;
    }

    public JTextPane getInstructionTextPane() {
        return instructionTextPane;
    }

    public JButton getLaunchSiteButton() {
        return launchSiteButton;
    }

    public JButton getSubmitButton() {
        return submitButton;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public JSeparator getTitleSeparator() {
        return titleSeparator;
    }

}
